config/routes.rb
Rails.application.routes.draw do
  post 'peticion_json/contribuyentes'
  post 'peticion_json/establecimientos'
  post 'peticion_json/proveedores'
  post 'peticion_json/tipos_de_gastos'
  devise_for :usuarios, controllers: {registrations: "registrations"}
  resources :configs, only: :update
  resources :libro_ventas
  resources :ventas
  resources :tipo_de_gastos
  resources :proveedors
  resources :compras
  resources :libro_compras
  resources :establecimientos
  resources :contribuyentes
  get 'inicio/index'
  

   root 'inicio#index'

end

app/models/libro_venta.rb
class LibroVenta < ActiveRecord::Base
  belongs_to :establecimiento
  has_many :ventas
end

app/controllers/libro_ventas_controller.rb
class LibroVentasController < ApplicationController
  before_action :set_libro_venta, only: [:show, :edit, :update, :destroy]
  before_action :set_ventas

  # GET /libro_ventas
  # GET /libro_ventas.json
  def index
    @libro_ventas = LibroVenta.all
  end

  # GET /libro_ventas/1
  # GET /libro_ventas/1.json
  def show
  end

  # GET /libro_ventas/new
  def new
    @libro_venta = LibroVenta.new
  end

  # GET /libro_ventas/1/edit
  def edit
  end

  # POST /libro_ventas
  # POST /libro_ventas.json
  def create
    @libro_venta = LibroVenta.new(libro_venta_params)

    respond_to do |format|
      if @libro_venta.save
        format.html { redirect_to @libro_venta, notice: 'Libro venta was successfully created.' }
        format.json { render :show, status: :created, location: @libro_venta }
      else
        format.html { render :new }
        format.json { render json: @libro_venta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libro_ventas/1
  # PATCH/PUT /libro_ventas/1.json
  def update
    respond_to do |format|
      if @libro_venta.update(libro_venta_params)
        format.html { redirect_to @libro_venta, notice: 'Libro venta was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro_venta }
      else
        format.html { render :edit }
        format.json { render json: @libro_venta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libro_ventas/1
  # DELETE /libro_ventas/1.json
  def destroy
    @libro_venta.destroy
    respond_to do |format|
      format.html { redirect_to libro_ventas_url, notice: 'Libro venta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro_venta
      @libro_venta = LibroVenta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_venta_params
      params.require(:libro_venta).permit(:establecimiento_id, :mes, :year)
    end

    def set_ventas
      # @iva = @libro_venta.ventas.sum(:iva)
      # @base = @libro_venta.ventas.sum(:base)
      # @bienes = (@libro_venta.ventas.sum(:bienes).to_f / 1.12).round(2)
      # servicios = (@libro_venta.ventas.sum(:servicios).to_f / 1.12).round(2)
      @ventas_por_dia = @libro_venta.ventas.order(:dia).group(:dia).sum(:base)
      dias = @libro_venta.ventas.order(:dia).group(:dia).count()

      @ventas = []

      dias.each do |dia|
        numero_dia = dia[0]
        cantidad_ventas = dia[1]
        if cantidad_ventas == 1
          venta_unica = @libro_venta.ventas.find_by(dia: numero_dia).as_json
          venta_unica["min"] = venta_unica["numero"]
          venta_unica["max"] = venta_unica["numero"]
          @ventas.push venta_unica
        else
          series = @libro_venta.ventas(dia: dia[0]).group(:serie).count()
          series.each do |serie|
            resumen_dia_ventas = {}
            resumen_dia_ventas['base']  = @libro_venta.ventas(dia: numero_dia, serie: serie).sum(:base)
            resumen_dia_ventas['bienes'] = @libro_venta.ventas(dia: numero_dia, serie: serie).sum(:bienes)
            resumen_dia_ventas['servicios'] = @libro_venta.ventas(dia: numero_dia, serie: serie).sum(:servicios)
            resumen_dia_ventas['documento'] = 'FC'
            resumen_dia_ventas['numero']  = 'Pendiente'
            resumen_dia_ventas['dia'] = numero_dia
            resumen_dia_ventas['mes'] = current_usuario.config.mes
            resumen_dia_ventas['year'] = current_usuario.config.year
            resumen_dia_ventas['nit'] = 'C/F'
            resumen_dia_ventas['nombre'] = "Clientes Varios"
            resumen_dia_ventas['min'] = @libro_venta.ventas(dia: numero_dia, serie: serie).minimum(:numero)
            resumen_dia_ventas['max'] = @libro_venta.ventas(dia: numero_dia, serie: serie).maximum(:numero)
            resumen_dia_ventas['serie'] = serie[0]

            @ventas.push resumen_dia_ventas.as_json
          end
        end
      end
      return @ventas
      
    end
  end

app/helpers/libro_ventas_helper.rb
module LibroVentasHelper
end

app/views/libro_ventas/_form.html.erb
<%= form_for(@libro_venta) do |f| %>
  <% if @libro_venta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro_venta.errors.count, "error") %> prohibited this libro_venta from being saved:</h2>

      <ul>
      <% @libro_venta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :establecimiento_id %><br>
    <%= f.text_field :establecimiento_id %>
  </div>
  <div class="field">
    <%= f.label :mes %><br>
    <%= f.number_field :mes %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libro_ventas/edit.html.erb
<h1>Editing Libro Venta</h1>

<%= render 'form' %>

<%= link_to 'Show', @libro_venta %> |
<%= link_to 'Back', libro_ventas_path %>

app/views/libro_ventas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Libro Ventas</h1>

<table>
  <thead>
    <tr>
      <th>Establecimiento</th>
      <th>Mes</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libro_ventas.each do |libro_venta| %>
      <tr>
        <td><%= libro_venta.establecimiento %></td>
        <td><%= libro_venta.mes %></td>
        <td><%= libro_venta.year %></td>
        <td><%= link_to 'Show', libro_venta %></td>
        <td><%= link_to 'Edit', edit_libro_venta_path(libro_venta) %></td>
        <td><%= link_to 'Destroy', libro_venta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro venta', new_libro_venta_path %>

app/views/libro_ventas/new.html.erb
<h1>New Libro Venta</h1>

<%= render 'form' %>

<%= link_to 'Back', libro_ventas_path %>

app/views/libro_ventas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Establecimiento:</strong>
  <%= @libro_venta.establecimiento.nombre %>
</p>

<p>
  <strong>Mes:</strong>
  <%= @libro_venta.mes %>
</p>

<p>
  <strong>Year:</strong>
  <%= @libro_venta.year %>
</p>
<table class="highlight">
  <thead>
    <tr>
      <th colspan="7"></th>
      <th colspan="2" class="center-align">Valor</th>
      <th colspan="3"></th>
    </tr>
    <tr>
      <th>Doc</th>
      <th>Serie</th>
      <th>Numero</th>
      <th>Nit</th>
      <th>Nombre</th>
      <th>Base</th>
      <th>Iva</th>
      <th>Bienes</th>
      <th>Servicios</th>
      <th>Total</th>
      <th colspan="2" class="center-align">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @libro_venta.ventas.each do |venta| %>
    <tr class="no-border-top">
      <td><%= venta.documento %></td>
      <td><%= venta.serie %></td>
      <td><%= venta.numero %></td>
      <td><%= venta.nit %></td>
      <td><%= venta.nombre %></td>
      <td><%= venta.base %></td>
      <td><%= venta.iva %></td>
      <td><%= venta.bienes %></td>
      <td><%= venta.servicios %></td>
      <td><%= venta.total %></td>
      <td class="">
        <%= link_to content_tag(:i ,'edit',class:"material-icons"), edit_venta_path(venta) ,class:"teal-text text-darken-3" %>
      </td>
      <td class="">
        <%= link_to content_tag(:i ,'delete_forever',class:"material-icons"), venta, method: :delete, data: { confirm: 'Estas seguro?' },class:"red-text text-darken-4" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>


<%= link_to new_venta_path, class:"waves-effect waves-light btn cyan darken-4 btn-floating" do %>
	<i class="material-icons left">arrow_back</i>
<%end%>