config/routes.rb
Rails.application.routes.draw do
  post 'peticion_json/contribuyentes'
  post 'peticion_json/establecimientos'
  post 'peticion_json/proveedores'
  post 'peticion_json/tipos_de_gastos'
  devise_for :usuarios, controllers: {registrations: "registrations"}
  resources :configs, only: :update
  resources :libro_ventas
  resources :ventas
  resources :tipo_de_gastos
  resources :proveedors
  resources :compras
  resources :libro_compras
  resources :establecimientos
  resources :contribuyentes
  get 'inicio/index'
  

   root 'inicio#index'

end

app/models/libro_compra.rb
class LibroCompra < ActiveRecord::Base
  belongs_to :establecimiento
  has_many :compras
end

app/controllers/libro_compras_controller.rb
class LibroComprasController < ApplicationController
  before_action :set_libro_compra, only: [:show, :edit, :update, :destroy]
  before_action :set_compras

  # GET /libro_compras
  # GET /libro_compras.json
  def index
    @libro_compras = LibroCompra.all
  end

  # GET /libro_compras/1
  # GET /libro_compras/1.json
  def show
  end

  # GET /libro_compras/new
  def new
    @libro_compra = LibroCompra.new
  end

  # GET /libro_compras/1/edit
  def edit
  end

  # POST /libro_compras
  # POST /libro_compras.json
  def create
    @libro_compra = LibroCompra.new(libro_compra_params)

    respond_to do |format|
      if @libro_compra.save
        format.html { redirect_to @libro_compra, notice: 'Libro compra was successfully created.' }
        format.json { render :show, status: :created, location: @libro_compra }
      else
        format.html { render :new }
        format.json { render json: @libro_compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libro_compras/1
  # PATCH/PUT /libro_compras/1.json
  def update
    respond_to do |format|
      if @libro_compra.update(libro_compra_params)
        format.html { redirect_to @libro_compra, notice: 'Libro compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro_compra }
      else
        format.html { render :edit }
        format.json { render json: @libro_compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libro_compras/1
  # DELETE /libro_compras/1.json
  def destroy
    @libro_compra.destroy
    respond_to do |format|
      format.html { redirect_to libro_compras_url, notice: 'Libro compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro_compra
      @libro_compra = LibroCompra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_compra_params
      params.require(:libro_compra).permit(:establecimiento_id, :mes, :year)
    end

    def set_compras
      @iva = @libro_compra.compras.sum(:iva)
      @base = @libro_compra.compras.sum(:base)
      @compras_por_dia = @libro_compra.compras.order(:dia)
      @total = @base + @iva
      @total_cuentas = @libro_compra.compras.count

    end
  end

app/helpers/libro_compras_helper.rb
module LibroComprasHelper
end

app/views/libro_compras/_form.html.erb
<%= form_for(@libro_compra) do |f| %>
  <% if @libro_compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro_compra.errors.count, "error") %> prohibited this libro_compra from being saved:</h2>

      <ul>
      <% @libro_compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :establecimiento_id %><br>
    <%= f.text_field :establecimiento_id %>
  </div>
  <div class="field">
    <%= f.label :mes %><br>
    <%= f.text_field :mes %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libro_compras/edit.html.erb
<h1>Editing Libro Compra</h1>

<%= render 'form' %>

<%= link_to 'Show', @libro_compra %> |
<%= link_to 'Back', libro_compras_path %>

app/views/libro_compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Libro Compras</h1>

<table>
  <thead>
    <tr>
      <th>Establecimiento</th>
      <th>Mes</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libro_compras.each do |libro_compra| %>
      <tr>
        <td><%= libro_compra.establecimiento.nombre %></td>
        <td><%= libro_compra.mes %></td>
        <td><%= libro_compra.year %></td>
        <td><%= link_to 'Show', libro_compra %></td>
        <td><%= link_to 'Edit', edit_libro_compra_path(libro_compra) %></td>
        <td><%= link_to 'Destroy', libro_compra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro compra', new_libro_compra_path %>

app/views/libro_compras/new.html.erb
<h1>New Libro Compra</h1>

<%= render 'form' %>

<%= link_to 'Back', libro_compras_path %>

app/views/libro_compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Establecimiento:</strong>
  <%= @libro_compra.establecimiento.nombre %>
</p>

<p>
  <strong>Mes:</strong>
  <%= @libro_compra.mes %>
</p>

<p>
  <strong>Year:</strong>
  <%= @libro_compra.year %>
</p>

<table class="centered">
  <thead>
    <tr>
      <th colspan="7"></th>
      <th colspan="2" class="center-align">Valor</th>
      <th colspan="3"></th>
    </tr>
    <tr>
      <th>Doc</th>
      <th>Serie</th>
      <th>Numero</th>
      <th>Nit</th>
      <th>Nombre</th>
      <th>Base</th>
      <th>Iva</th>
      <th>Bienes</th>
      <th>Servicios</th>
      <th>Total</th>
      <th colspan="2">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @libro_compra.compras.each do |compra| %>
    <tr class="no-border-top">
      <td><%= compra.documento %></td>
      <td><%= compra.serie %></td>
      <td><%= compra.numero %></td>
      <td><%= compra.proveedor.nit %></td>
      <td><%= compra.proveedor.nombre %></td>
      <td><%= compra.base %></td>
      <td><%= compra.iva %></td>
      <td><%= compra.bienes %></td>
      <td><%= compra.servicios %></td>
      <td><%= compra.total %></td>
      <td class="">
        <%= link_to content_tag(:i ,'edit',class:"material-icons"), edit_compra_path(compra) ,class:"teal-text text-darken-3" %>
      </td>
      <td class="">
        <%= link_to content_tag(:i ,'delete_forever',class:"material-icons"), compra, method: :delete, data: { confirm: 'Estas seguro?' },class:"red-text text-darken-4" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_compra_path, class:"waves-effect waves-light btn cyan darken-4 btn-floating" do %>
	<i class="material-icons left">arrow_back</i>
<%end%>