config/routes.rb
Rails.application.routes.draw do
  post 'peticion_json/contribuyentes'
  post 'peticion_json/establecimientos'
  post 'peticion_json/proveedores'
  post 'peticion_json/tipos_de_gastos'
  devise_for :usuarios, controllers: {registrations: "registrations"}
  resources :configs, only: :update
  resources :libro_ventas
  resources :ventas
  resources :tipo_de_gastos
  resources :proveedors
  resources :compras
  resources :libro_compras
  resources :establecimientos
  resources :contribuyentes
  get 'inicio/index'
  

   root 'inicio#index'

end

app/models/tipo_de_gasto.rb
class TipoDeGasto < ActiveRecord::Base
	has_many :compras

	validates :nombre, presence: true, uniqueness: { case_sensitive: true, message:" repetido, ya existe esta cuenta" }
end

app/controllers/tipo_de_gastos_controller.rb
class TipoDeGastosController < ApplicationController
  before_action :set_tipo_de_gasto, only: [:show, :edit, :update, :destroy]

  # GET /tipo_de_gastos
  # GET /tipo_de_gastos.json
  def index
    @tipo_de_gastos = TipoDeGasto.all
  end

  # GET /tipo_de_gastos/1
  # GET /tipo_de_gastos/1.json
  def show
  end

  # GET /tipo_de_gastos/new
  def new
    @tipo_de_gasto = TipoDeGasto.new
  end

  # GET /tipo_de_gastos/1/edit
  def edit
  end

  # POST /tipo_de_gastos
  # POST /tipo_de_gastos.json
  def create
    @tipo_de_gasto = TipoDeGasto.new(tipo_de_gasto_params)

    respond_to do |format|
      if @tipo_de_gasto.save
        format.html { redirect_to @tipo_de_gasto, notice: 'Tipo de gasto was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_de_gasto }
      else
        format.html { render :new }
        format.json { render json: @tipo_de_gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_de_gastos/1
  # PATCH/PUT /tipo_de_gastos/1.json
  def update
    respond_to do |format|
      if @tipo_de_gasto.update(tipo_de_gasto_params)
        format.html { redirect_to @tipo_de_gasto, notice: 'Tipo de gasto was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_de_gasto }
      else
        format.html { render :edit }
        format.json { render json: @tipo_de_gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_de_gastos/1
  # DELETE /tipo_de_gastos/1.json
  def destroy
    @tipo_de_gasto.destroy
    respond_to do |format|
      format.html { redirect_to tipo_de_gastos_url, notice: 'Tipo de gasto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_de_gasto
      @tipo_de_gasto = TipoDeGasto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_de_gasto_params
      params.require(:tipo_de_gasto).permit(:nombre)
    end
end

app/helpers/tipo_de_gastos_helper.rb
module TipoDeGastosHelper
end

app/views/tipo_de_gastos/_form.html.erb
<%= form_for(@tipo_de_gasto) do |f| %>
<% if @tipo_de_gasto.errors.any? %>
<div class="card-panel">

  <p class="cyan-text text-darken-4">No se puede guardar la información:</p>

  <ul>
    <% @tipo_de_gasto.errors.full_messages.each do |message| %>
    <li class="red-text -text-darken-4"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="input-field col s4 offset-s4">
    <i class="material-icons prefix">receipt</i>
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions row">
    <div class="col s4 offset-s4 center-align">
      <%= f.submit class:"btn waves-effect waves-teal", value:"Enviar" %>
    </div>
  </div>
  <% end %>

app/views/tipo_de_gastos/edit.html.erb
<h1>Editing Tipo De Gasto</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_de_gasto %> |
<%= link_to 'Back', tipo_de_gastos_path %>

app/views/tipo_de_gastos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos De Gastos</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="1">Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_de_gastos.each do |tipo_de_gasto| %>
    <tr>
      <td><%= tipo_de_gasto.nombre %></td>
      <!--<td><%= link_to 'Show', tipo_de_gasto %></td>-->
      <td>
        <%= link_to edit_tipo_de_gasto_path(tipo_de_gasto) do %>
        <i class="material-icons">edit</i>
        <% end %>  

        <!--<td>
          <%= link_to tipo_de_gasto, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="material-icons red-text">delete</i>
          <% end %>
        </td>-->
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="actions row">
    <div class="col s4 offset-s4 center-align">
      <%= link_to 'Nuevo Tipo de Gasto', new_tipo_de_gasto_path, class:"btn waves-effect waves-teal" %>
    </div>
  </div>
  

app/views/tipo_de_gastos/new.html.erb
<div class="row">
	<div class="col s8 offset-s2 center-align">
		<h1>Añadir Tipo de Gasto</h1>
	</div>
</div>

<%= render 'form' %>

<%= link_to root_path, class:"waves-effect waves-light btn cyan darken-4 btn-floating" do %>
	<i class="material-icons left">arrow_back</i>
<%end%>

app/views/tipo_de_gastos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo_de_gasto.nombre %>
</p>

<%= link_to 'Edit', edit_tipo_de_gasto_path(@tipo_de_gasto) %> |
<%= link_to 'Back', tipo_de_gastos_path %>