config/routes.rb
Rails.application.routes.draw do
  post 'peticion_json/contribuyentes'
  post 'peticion_json/establecimientos'
  post 'peticion_json/proveedores'
  post 'peticion_json/tipos_de_gastos'
  devise_for :usuarios, controllers: {registrations: "registrations"}
  resources :configs, only: :update
  resources :libro_ventas
  resources :ventas
  resources :tipo_de_gastos
  resources :proveedors
  resources :compras
  resources :libro_compras
  resources :establecimientos
  resources :contribuyentes
  get 'inicio/index'
  

   root 'inicio#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SistemaContable</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<nav>
		<div class="nav-wrapper">

			<%= link_to  inicio_index_path, class:"brand-logo waves-effect waves-light" do %>
			<i class="material-icons">home</i> Inicio
			<%end%>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<%if usuario_signed_in? %>
				<<!-- li>
					<a href="#" class="waves-effect waves-light"><%= @l_ventas.nil?%></a>
				</li> -->
				<li>
					<a href="#" class="waves-effect waves-light"><%= contribuyente %></a>
				</li>
				<li>
					<a href="#" class="waves-effect waves-light"><%= establecimiento %></a>
				</li>
				<li>
					<a href="#" class="waves-effect waves-light"><%= mes %></a>
				</li>
				<li>
					<a href="#" class="waves-effect waves-light"><%= current_usuario.config.year == 0 || current_usuario.config.year.nil? ? "Año" : current_usuario.config.year %></a>
				</li>
				
				<li>
					<a id="dialog-edit-btn" class="mdl-button mdl-js-button mdl-button--accent">
						<i class="material-icons">edit</i>
					</a>
					<%= render '/dialog'%>
						</li>

						<li><%= link_to "Cerrar Sesion", destroy_usuario_session_path, :method => :delete, class:"waves-effect waves-light"%></li>
						<%end%>
					</ul>
				</div>
			</nav>

			<div class="container">

				<%= yield %>
			</div>

		</body>
		</html>